services:

  drill-metabase-dashboards-migration:
    image: ghcr.io/drill4j/drill-metabase-dashboards:${DRILL_METABASE_DASHBOARDS_VERSION}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL: ${POSTGRES_SSL}
      METABASE_DB_NAME: ${METABASE_DB_NAME}
      DRILL_METRICS_DB_NAME: ${DRILL_METRICS_DB_NAME}
      DRILL_UI_BASE_URL: ${DRILL_UI_BASE_URL}
      DRILL_METRICS_UI_BASE_URL: ${DRILL_METRICS_UI_BASE_URL}
    networks:
      - docker_default  # Specify network on which PostgreSQL container is running

networks:
  docker_default:
    external: true