name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag / Version for the Docker image. Example: 0.9.0"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish to Registry
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.GH_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
          registry: ghcr.io
          repository: drill4j/drill-metabase-dashboards
          tags: latest,${{ github.event.inputs.version }}
          build_args: ENV=development,VERSION=${{ github.event.inputs.version }}

      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.ref_name != 'main' }}
